site_name: Reference System Documentation
site_url: https://ros-realtime.github.io/reference-system/
site_author: Evan Flynn
repo_url: https://github.com/ros-realtime/reference-system.git
theme:
  name: 'material'
  features:
    - navigation.indexes
    - navigation.tracking
plugins:
  - search
  - awesome-pages
extra:
  version:
    provider: mike
